# Generated by Django 2.2.4 on 2019-10-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
