# Generated by Django 2.2.4 on 2019-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='group_ids',
            field=models.CharField(default='Individual Event', max_length=256),
            preserve_default=False,
        ),
    ]
