# Generated by Django 2.2.4 on 2019-10-22 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0003_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
