# Generated by Django 2.2.4 on 2019-10-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0004_auto_20191022_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='acheivements',
        ),
    ]
