# Generated by Django 2.2.4 on 2019-10-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0005_remove_registrations_acheivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default='2019-10-15'),
        ),
    ]
