# Generated by Django 2.2.4 on 2019-12-16 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0011_auto_20191216_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2019, 12, 16, 15, 55, 16, 785153)),
        ),
    ]
