# Generated by Django 2.2.4 on 2020-01-08 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0012_auto_20191216_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 1, 8, 10, 58, 19, 589933)),
        ),
    ]
