# Generated by Django 2.2.4 on 2020-01-08 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0013_auto_20200108_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='rej_reason',
            field=models.TextField(default='Sorry, kindly submit your application for future attempts.'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 1, 8, 17, 44, 56, 915520)),
        ),
    ]
