# Generated by Django 2.2.4 on 2020-01-09 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0015_auto_20200108_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 1, 9, 18, 58, 10, 141875)),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='rej_reason',
            field=models.TextField(default='Sorry, your application has not been accepted.', null=True),
        ),
    ]
