# Generated by Django 2.2.4 on 2020-01-09 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0016_auto_20200109_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 1, 9, 21, 40, 26, 941594)),
        ),
    ]
