# Generated by Django 2.2.4 on 2020-01-30 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0021_auto_20200129_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 5, 39, 47, 158314)),
        ),
    ]
