# Generated by Django 2.2.4 on 2019-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=64)),
                ('teacher_incharge', models.CharField(max_length=64)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('event_information', models.TextField(blank=True)),
                ('event_dates', models.TextField()),
                ('single_check', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubEvents',
            fields=[
                ('subevent_id', models.AutoField(primary_key=True, serialize=False)),
                ('subevent_name', models.CharField(max_length=64)),
                ('subevent_dates', models.CharField(max_length=64)),
                ('subevent_type', models.CharField(default='I', max_length=1)),
                ('event_id', models.IntegerField()),
                ('total_slots', models.IntegerField(default=0)),
                ('total_registrations', models.IntegerField(default=0)),
                ('maximum_students', models.IntegerField(default=0)),
                ('selected_students', models.IntegerField(default=0)),
                ('selected_student_ids', models.TextField(blank=True)),
                ('subevent_information', models.TextField(blank=True)),
                ('subevent_requirements', models.TextField(blank=True)),
                ('subevent_teacher_incharge', models.CharField(max_length=64)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('allowed_grades', models.CharField(default='ALL', max_length=32)),
            ],
        ),
    ]
