# Generated by Django 2.2.4 on 2019-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='registered_student_ids',
            field=models.TextField(blank=True),
        ),
    ]
