# Generated by Django 2.2.4 on 2019-10-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0002_subevents_registered_student_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_attachment',
            field=models.FileField(default='', upload_to='Attachements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subevents',
            name='subevent_attachment',
            field=models.FileField(default='event_info.txt', upload_to='Attachements'),
            preserve_default=False,
        ),
    ]
