# Generated by Django 2.2.4 on 2019-10-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0004_auto_20191014_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevents',
            name='registered_student_ids',
        ),
        migrations.RemoveField(
            model_name='subevents',
            name='selected_student_ids',
        ),
    ]
