# Generated by Django 2.2.4 on 2019-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0005_auto_20191017_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='category',
            field=models.CharField(default='IT', max_length=32),
            preserve_default=False,
        ),
    ]
