# Generated by Django 2.2.4 on 2019-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0007_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='teacher_incharge_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subevents',
            name='subevent_teacher_incharge_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
