# Generated by Django 2.2.4 on 2019-10-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0008_auto_20191018_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='log_in_check',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
