# Generated by Django 2.2.4 on 2019-10-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0009_status_log_in_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='log_in_check',
        ),
    ]
