# Generated by Django 2.2.4 on 2019-10-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0010_remove_status_log_in_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='acheivements',
            field=models.TextField(default=''),
        ),
    ]
