# Generated by Django 2.2.4 on 2019-10-19 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0011_status_acheivements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
