# Generated by Django 2.2.4 on 2019-10-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0013_auto_20191019_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='department',
            field=models.CharField(default='Computer Science', max_length=64),
            preserve_default=False,
        ),
    ]
