# Generated by Django 2.2.4 on 2019-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0014_status_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_attachment',
            field=models.FileField(blank=True, default='', upload_to='Attachments'),
        ),
        migrations.AlterField(
            model_name='subevents',
            name='subevent_attachment',
            field=models.FileField(blank=True, default='', upload_to='Attachments'),
        ),
    ]
