# Generated by Django 2.2.4 on 2019-10-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0015_auto_20191022_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_attachment',
            field=models.FileField(default='', upload_to='Attachments'),
        ),
        migrations.AlterField(
            model_name='subevents',
            name='subevent_attachment',
            field=models.FileField(default='', upload_to='Attachments'),
        ),
    ]
