# Generated by Django 2.2.4 on 2019-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0016_auto_20191022_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='confirmation_status',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
