# Generated by Django 2.2.4 on 2019-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0018_subevents_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevents',
            name='group_size',
            field=models.IntegerField(null=True),
        ),
    ]
