# Generated by Django 2.2.4 on 2019-11-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0019_auto_20191027_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='acheivements',
            new_name='achievements',
        ),
    ]
