# Generated by Django 2.2.4 on 2020-01-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0020_auto_20191103_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_attachment',
            field=models.FileField(blank=True, upload_to='Attachments'),
        ),
        migrations.AlterField(
            model_name='subevents',
            name='subevent_attachment',
            field=models.FileField(blank=True, upload_to='Attachments'),
        ),
    ]
