# Generated by Django 2.2.4 on 2020-01-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherview', '0022_auto_20200109_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='subevents',
            options={'verbose_name_plural': 'SubEvents'},
        ),
    ]
